
package com.java.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Hello", targetNamespace = "http://webservice.java.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hello {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://webservice.java.com/", className = "com.java.webservice.Hello_Type")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://webservice.java.com/", className = "com.java.webservice.HelloResponse")
    @Action(input = "http://webservice.java.com/Hello/helloRequest", output = "http://webservice.java.com/Hello/helloResponse")
    public String hello(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

}
